### PR TITLE
Flow ebos sync with flow legacy

### PR DESCRIPTION
**Pull request by andlaus**
this synchronizes SimulatorFullyImplicitBlackoilEbos with the flow_legacy version (SimulatorFullyImplicitBlackoil). this PR contains the first two patches of what used to be #1025. (that stuff was unrelated to the fluid in place functionality.)

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins run norne_ebos please

**Comment by atgeirr** [comment]
Seems to cause a segfault on Jenkins, which must be fixed before we can merge this.

**Comment by andlaus** [comment]
fixed. it was caused by issue in the FIP code which has also been solved by #1025. This PR will thus cause some merge conflicts with #1025 and the present PR should be merged first for this reason.

**Comment by andlaus** [comment]
jenkins run norne_ebos please

File: opm/autodiff/BlackoilModelEbos.hpp [hunk 1]
```diff
@@ -1000,21 +1001,32 @@ namespace Opm {
...
 
-            for (int c = 0; c < nc; ++c) {
-                const auto& intQuants = *ebosSimulator_.model().cachedIntensiveQuantities(c, /*timeIdx=*/0);
+            ElementContext elemCtx(ebosSimulator_);
+            auto elemIt = elemCtx.gridView().template begin</*codim=*/0>();
+            const auto& elemEndIt = elemCtx.gridView().template end</*codim=*/0>();
+            for (; elemIt != elemEndIt; ++elemIt) {
+                const auto& elem = *elemIt;
+                if (elem.partitionType() != Dune::InteriorEntity)
+                    continue;
```
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: Braces please (unless you can get rid of the if as described above).

File: opm/autodiff/BlackoilModelEbos.hpp [hunk 2]
```diff
@@ -1000,21 +1001,32 @@ namespace Opm {
                 fip_.fip[i].resize(nc,0.0);
             }
 
-            for (int c = 0; c < nc; ++c) {
-                const auto& intQuants = *ebosSimulator_.model().cachedIntensiveQuantities(c, /*timeIdx=*/0);
+            ElementContext elemCtx(ebosSimulator_);
+            auto elemIt = elemCtx.gridView().template begin</*codim=*/0>();
+            const auto& elemEndIt = elemCtx.gridView().template end</*codim=*/0>();
+            for (; elemIt != elemEndIt; ++elemIt) {
```
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: Would not this loop be better as
```
for (const auto& elem : elements(elemCtx.gridView(), Dune::InteriorEntity)) {
```
That would also avoid the if() below.

Also: is this verified to be correct in parallel? (It looks reasonable, but I am not sure.)

File: opm/autodiff/BlackoilModelEbos.hpp [hunk 3]
```diff
@@ -1000,21 +1001,32 @@ namespace Opm {
...
+                const auto& elem = *elemIt;
+                if (elem.partitionType() != Dune::InteriorEntity)
+                    continue;
+
+                elemCtx.updatePrimaryStencil(elem);
```
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: To clarify: does this change the elemCtx to refer to `elem` somehow?

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 2 above)
Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: the last time I tried to loop over a specific partition with Dune, it did not work. I don't remember what the problem was and I have to admit that this was at about the time when Dune 2.1 was current.

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 1 above)
Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: right. I always forget about them. Fixed.

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 3 above)
Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: yes: it update the stencil to correspond to `elem`. the next line "attaches" the intensive quantities of the latest sub-solution for the central DOF of the stencil. (i.e., for the element-centered finite volume method this is the element itself)

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 2 above)
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: Hmmm... If that does not work it would be quite serious -- it is the main way to interact with a dune grid these days I believe, and the partition stuff is the main way to deal with parallelism in the interface. Could you give it a shot?

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 3 above)
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: I have to admit this part is not very intuitive... (I'm just looping over the cells, why do I need to update a stencil?!?) I'll accept the code though now that I understand what it does (but wishing for improvements in the future).

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 2 above)
Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: It is very well possible that this has been working as advertised for a while. (if yes, does it work properly with `Dune::CpGrid`?) In general, my impression is that the parallel stuff is pretty much an afterthought for most Dune people and it thus does not get tested as well as the rest. I cannot really blame them for this ;)

> Could you give it a shot?

yes, I'll try. a problem may be that I cannot really test this in parallel because of the other MPI issues we have...

Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: ok. with `Dune::CpGrid` it does not work: it says

```
error: ‘elements’ was not declared in this scope
```

the same story applies if `Dune::elements()` is used. that seems to be an issue with `Dune::CpGrid`? (also, would it work with Dune 2.3? If no, this could be a good reason to raise the Dune requirement to 2.4...)

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 3 above)
Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: I agree that it is not very intuitive, so let me try to explain: the stencil is needed because without it, the intensive quantities cannot be calculated. that said, updating the central part of the stencil for the ECFV discretization is very cheap: it basically just stores the Dune entity for the element.

If one is lazy and does not care too much about performance, one can use
```
elemCtx.updateAll(elem);
```

but this updates all data (i.e. intensive and extensive quantities) for all DOFs of the stencil on all substeps. since only the intensive quantities for the most recent substep and only for the central element is needed here, it is done like it is...

File: opm/autodiff/BlackoilModelEbos.hpp (hunk 2 above)
Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: I'd like this to work with CpGrid, perhaps @dr-robertk or @blattms could enlighten us?

Comment (andlaus) [inline opm/autodiff/BlackoilModelEbos.hpp]: +1. I've also checked: it seems like ranged-based loops over entities were only introduced in the Dune 2.4 release.

how shall we with proceed with the present PR? merge it as-is or wait a bit?

Comment (atgeirr) [inline opm/autodiff/BlackoilModelEbos.hpp]: If the helpers were only introduced in 2.4 we should merge this now. It is unfortunate that somewhat complex grid-iteration code leaks into this though, but for now it will have to do.
